### ISSUE TITLE
NegativeArraySizeException on attempt to transform IntCache;getIntCache(I)[I

### ISSUE THREAD

**Issue by Foghrye4** [Foghrye4/CWGFarPlaneView#1]
```
Caused by: java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at cwgfarplaneview.core.CWGFPVClassTransformer.transformGenLayerChilds(CWGFPVClassTransformer.java:47)
	at cwgfarplaneview.core.CWGFPVClassTransformer.transform(CWGFPVClassTransformer.java:22)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 45 more```

I have no idea what I'm doing wrong here:
https://github.com/Foghrye4/CWGFarPlaneView/blob/master/src/main/java/cwgfarplaneview/core/GenLayerChildClassVisitor.java#L21

**Comment by Foghrye4** [comment]
Fixed.
